### ISSUE TITLE
Unable to import module marshmallow_pyspark on azure synapse analytics

### ISSUE THREAD

**Issue by gabiszigeti** [ketgo/marshmallow-pyspark#7]
After installing marshmallow pyspark on azure synapse analytics, when I am trying to import the module I receive a module not found error.

installation:
`%pip install marshmallow-pyspark`
`from marshmallow_pyspark import Schema`

error:
`PythonException: 
  An exception was thrown from the Python worker. Please see the stack trace below.
Traceback (most recent call last):
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 603, in main
    func, profiler, deserializer, serializer = read_udfs(pickleSer, infile, eval_type)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 449, in read_udfs
    udfs.append(read_single_udf(pickleSer, infile, eval_type, runner_conf, udf_index=i))
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 251, in read_single_udf
    f, return_type = read_command(pickleSer, infile)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/worker.py", line 71, in read_command
    command = serializer._read_with_length(file)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 160, in _read_with_length
    return self.loads(obj)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 430, in loads
    return pickle.loads(obj, encoding=encoding)
ModuleNotFoundError: No module named 'marshmallow_pyspark'`

Is it possible that some dependencies need to be updated and that causes this error?

Thank you!

**Comment by ketgo** [comment]
Hi @gabiszigeti, is it possible the package was not installed properly on the workers? The stack trace shows an import error.

**Comment by ketgo** [comment]
Closing issue as stale.
